SELECT 
    F.RAZAO_FOR AS RAZAO , 
	CP.DTVENCTO_CTP AS VENCIMENTO, 
	    CASE
	    	WHEN CC.TIPO = 'A' THEN CC.CONTA 
	    END AS CONTA ,
	    CASE 
	    	WHEN CC.TIPO = 'A' THEN SUBSTRING(CC.CONTA FROM 1 FOR 3) --retorna somente 3 primeiros caracteres da coluna
	    END AS TIPO ,
	EXTRACT(YEAR FROM CP.DTVENCTO_CTP) AS ANO , 
	CP.DATA_CTP AS DATA_CPT ,
	CP.VALOR_CTP ,
	CC.DESCRICAO
FROM CONTAS_PAGAR cp 
LEFT JOIN FORNECEDOR f ON CP.COD_FOR = F.COD_FOR 
LEFT JOIN CONTAS_PAGAR_CENTRO_CUSTO ccp ON CP.COD_CPT = CCP.COD_CPT 
LEFT JOIN CENTRO_CUSTO cc ON CCP.CODIGO_CENTRO_CUSTO  = CC.CODIGO 
