CASE 
    WHEN DATEDIFF(YEAR, DATA_NASCIMENTO, DATA_ATUAL) BETWEEN 17 AND 24 THEN 'A 18 A 24'
    WHEN DATEDIFF(YEAR, DATA_NASCIMENTO, DATA_ATUAL) BETWEEN 25 AND 40 THEN 'B 25 A 40'
    WHEN DATEDIFF(YEAR, DATA_NASCIMENTO, DATA_ATUAL) BETWEEN 41 AND 60 THEN 'C 41 A 60'
    WHEN DATEDIFF(YEAR, DATA_NASCIMENTO, DATA_ATUAL) > 60 THEN 'D SUPERIOR A 60'
END AS FAIXA_IDADE
