SELECT 
    CR.DATA_CTR AS DATA_EMISSAO ,
    CR.VENCTO_CTR AS DATA_VENCIMENTO ,
    C.NOME_CLI AS CLIENTE ,
    CR.VALOR_CTR AS VALOR_BRUTO , 
    CR.ACRESCIMO_CTR AS JUROS ,
    (CR.VALOR_CTR + CR.ACRESCIMO_CTR - CR.DESCONTO_CTR) AS VALOR_LIQUIDO , 
    (C.ENDCOM_CLI || ' / ' || C.BAIRES_CLI || ' / ' || C.CIDRES_CLI || ' / ' || C.CEPCOM_CLI || ' / ' || C.ESTCOM_CLI) AS ENDERECO , 
    EXTRACT(YEAR FROM CR.DATA_CTR) AS ANO
FROM CONTAS_RECEBER CR 
LEFT JOIN CLIENTE C ON CR.COD_CLI = C.COD_CLI 
WHERE 1=1
