CREATE VIEW V_LANCAMENTOS_BI AS 
SELECT 
	lcc2.DATAEMI_LAN AS data_emissao ,
	CAST (lcc2.DATA_LANCAMENTO AS date) AS data_lancamento ,
	cc.CONTA AS conta ,
	cc.DESCRICAO AS descricao ,
	CAST(ROUND(SUM(lcc.VALOR), 2) AS numeric(18, 2)) AS valor , 
	cc.RECEITA_DESPESA AS receita_despesa , 
	'Rap 10' AS empresa
FROM LANCAMENTOS_CENTRO_CUSTO lcc 
LEFT JOIN LANCAMENTOS_CONTAS_CORRENTE lcc2 ON lcc.COD_LAN = lcc2.COD_LAN 
LEFT JOIN CENTRO_CUSTO cc ON lcc.COD_CENTRO_CUSTO = cc.CODIGO 
WHERE 1=1
GROUP BY cc.CONTA , cc.DESCRICAO , lcc2.DATAEMI_LAN , lcc2.DATA_LANCAMENTO , cc.RECEITA_DESPESA
