
CREATE VIEW VW_ESTOQUE_ATUAL2 AS
SELECT 
P.PRO_CODI AS CODIGO_PRODUTO, 
P.PRO_DESC AS DESCRICAO_PRODUTO,
E.EST_QUAN AS QUANTIDADE_ESTOQUE 
FROM ESTOQUE E
INNER JOIN PRODUTO P ON E.PRO_CODI = P.PRO_CODI
INNER JOIN FORNECEDOR F ON P.FOR_CODI = F.FOR_CODI
INNER JOIN TBCUSTOMATE C ON P.PRO_CODI = C.MAT_CODI
WHERE E.LOC_CODI = '001'
AND P.DPT_CODI = '001'
AND P.PRO_SITU = 'A'
AND C.LOC_CODI = '001'
GROUP BY P.PRO_CODI, P.PRO_DESC, E.EST_QUAN


