SELECT 
    CODIGO_PRODUTO,
    PRODUTO,
    SUM(CASE WHEN DATA BETWEEN '01/09/2023' AND '30/09/2023' THEN QUANTIDADE END) AS QUANTIDADE,
    CAST(
        (
            SELECT SUM(QUANTIDADE) / 3
            FROM VW_FATURAMENTO_DETALHADO AS SubQuery
            WHERE DATA BETWEEN '01/06/2023' AND '31/08/2023'
            AND NATUREZA = 'VEN'
            AND SubQuery.CODIGO_PRODUTO = VW_FATURAMENTO_DETALHADO.CODIGO_PRODUTO
        ) AS INT
    ) AS MEDIA_ULTIMO_TRIMESTRE,  
    FOR_CODI, 
    FORNECEDOR 
FROM VW_FATURAMENTO_DETALHADO
WHERE LOCALIZACAO = '001'
AND FOR_CODI = 940
AND NATUREZA = 'VEN'
GROUP BY CODIGO_PRODUTO, PRODUTO, FOR_CODI, FORNECEDOR




SELECT 
    CODIGO_PRODUTO,
    PRODUTO,
    SUM(CASE WHEN DATA BETWEEN '01/09/2023' AND '30/09/2023' THEN QUANTIDADE END) AS QUANTIDADE,
    CAST(
        (
            SELECT SUM(QUANTIDADE) / 3
            FROM VW_FATURAMENTO_DETALHADO AS SubQuery
            WHERE DATA BETWEEN '01/06/2023' AND '31/08/2023'
            AND NATUREZA = 'VEN'
            AND SubQuery.CODIGO_PRODUTO = VW_FATURAMENTO_DETALHADO.CODIGO_PRODUTO
        ) AS INT
    ) AS MEDIA_ULTIMO_TRIMESTRE,  
    ((SUM(CASE WHEN DATA BETWEEN '01/09/2023' AND '30/09/2023' THEN QUANTIDADE END) - 
      CAST(
            (
                SELECT SUM(QUANTIDADE) / 3
                FROM VW_FATURAMENTO_DETALHADO AS SubQuery
                WHERE DATA BETWEEN '01/06/2023' AND '31/08/2023'
                AND NATUREZA = 'VEN'
                AND SubQuery.CODIGO_PRODUTO = VW_FATURAMENTO_DETALHADO.CODIGO_PRODUTO
            ) AS INT
        )) / NULLIF(CAST(
            (
                SELECT SUM(QUANTIDADE) / 3
                FROM VW_FATURAMENTO_DETALHADO AS SubQuery
                WHERE DATA BETWEEN '01/06/2023' AND '31/08/2023'
                AND NATUREZA = 'VEN'
                AND SubQuery.CODIGO_PRODUTO = VW_FATURAMENTO_DETALHADO.CODIGO_PRODUTO
            ) AS INT
        ), 0)) * 100 AS CRESCIMENTO_RELATIVO,
    FOR_CODI, 
    FORNECEDOR
FROM VW_FATURAMENTO_DETALHADO
WHERE LOCALIZACAO = '001'
AND FOR_CODI = 940
AND NATUREZA = 'VEN'	
GROUP BY CODIGO_PRODUTO, PRODUTO, FOR_CODI, FORNECEDOR
