SELECT 
    CODIGO_PRODUTO,
    PRODUTO,
    SUM(CASE WHEN DATA BETWEEN '01/09/2023' AND '30/09/2023' THEN QUANTIDADE END) AS QUANTIDADE,
    CAST(
        (
            SELECT SUM(QUANTIDADE) / 3
            FROM VW_FATURAMENTO_DETALHADO AS SubQuery
            WHERE DATA BETWEEN '01/06/2023' AND '31/08/2023'
            AND NATUREZA = 'VEN'
            AND SubQuery.CODIGO_PRODUTO = VW_FATURAMENTO_DETALHADO.CODIGO_PRODUTO
        ) AS INT
    ) AS MEDIA_ULTIMO_TRIMESTRE,  
    FOR_CODI, 
    FORNECEDOR 
FROM VW_FATURAMENTO_DETALHADO
WHERE LOCALIZACAO = '001'
AND FOR_CODI = 940
AND NATUREZA = 'VEN'
GROUP BY CODIGO_PRODUTO, PRODUTO, FOR_CODI, FORNECEDOR




--com erro

SELECT 
    CODIGO_PRODUTO,
    PRODUTO,
    SUM(CASE WHEN DATA BETWEEN '01/09/2023' AND '30/09/2023' THEN QUANTIDADE ELSE 0 END) AS QUANTIDADE,
    CAST(
        (
            SELECT SUM(QUANTIDADE) / 3
            FROM VW_FATURAMENTO_DETALHADO AS SubQuery
            WHERE DATA BETWEEN '01/06/2023' AND '31/08/2023'
            AND SubQuery.CODIGO_PRODUTO = VW_FATURAMENTO_DETALHADO.CODIGO_PRODUTO
        ) AS INT
    ) AS MEDIA_ULTIMO_TRIMESTRE,
    CAST(
        (
            (SUM(CASE WHEN DATA BETWEEN '01/09/2023' AND '30/09/2023' THEN QUANTIDADE ELSE 0 END) - CAST(
                (
                    SELECT SUM(QUANTIDADE) / 3
                    FROM VW_FATURAMENTO_DETALHADO AS SubQuery
                    WHERE DATA BETWEEN '01/06/2023' AND '31/08/2023'
                    AND SubQuery.CODIGO_PRODUTO = VW_FATURAMENTO_DETALHADO.CODIGO_PRODUTO
                ) AS INT
            )) / CAST(
                (
                    SELECT SUM(QUANTIDADE) / 3
                    FROM VW_FATURAMENTO_DETALHADO AS SubQuery
                    WHERE DATA BETWEEN '01/06/2023' AND '31/08/2023'
                    AND SubQuery.CODIGO_PRODUTO = VW_FATURAMENTO_DETALHADO.CODIGO_PRODUTO
                ) AS INT
            )
        ) * 100 AS CRESCIMENTO, --o sql server aponta erro aqui (Msg 102, Level 15, State 1, Line 30 Incorrect syntax near ','.)

    FOR_CODI, 
    FORNECEDOR,
    SECAO 
FROM VW_FATURAMENTO_DETALHADO
WHERE LOCALIZACAO = '001'
AND NATUREZA IN ('VEN', 'BOV')
GROUP BY CODIGO_PRODUTO, PRODUTO, FOR_CODI, FORNECEDOR, SECAO
