SELECT 
    CODIGO_PRODUTO,
    PRODUTO,
    SUM(CASE WHEN DATA BETWEEN '01/09/2023' AND '30/09/2023' THEN QUANTIDADE ELSE 0 END) AS QUANTIDADE,
    CAST(
        (
            SELECT SUM(QUANTIDADE) / 3
            FROM VW_FATURAMENTO_DETALHADO AS SubQuery
            WHERE DATA BETWEEN '01/06/2023' AND '31/08/2023'
            AND SubQuery.CODIGO_PRODUTO = VW_FATURAMENTO_DETALHADO.CODIGO_PRODUTO
        ) AS INT
    ) AS MEDIA_ULTIMO_TRIMESTRE,  
    FOR_CODI, 
    FORNECEDOR 
FROM VW_FATURAMENTO_DETALHADO
WHERE LOCALIZACAO = '001'
AND NATUREZA IN ('VEN', 'BOV')
GROUP BY CODIGO_PRODUTO, PRODUTO, FOR_CODI, FORNECEDOR
