CREATE VIEW VW_PRODUTO_NCM AS 
SELECT E.DESCRICAO_PRODUTO, P.PRO_NCM --SELECIONA COLUNAS DESCRIÇÃO E NCM DOS PRODUTOS
FROM ESTOQUE E
INNER JOIN PRODUTO P ON P.PRO_CODI = E.CODIGO_PRODUTO --RELACIONANDO DUAS TABELAS PELO CODIGO DO PRODUTO
WHERE P.PRO_SITU = 'A' --SOMENTE PRODUTOS ATIVOS
AND P.SEC_CODI = 009 --SOMENTE SEÇÃO PET 
