SELECT
    P.PRO_CODI,
    P.PRO_DESC,
    (
        SELECT SUM(FD.QUANTIDADE)
        FROM VW_FATURAMENTO_DETALHADO AS FD
        WHERE FD.CODIGO_PRODUTO = P.PRO_CODI
        AND FD.DATA BETWEEN '01/02/2023' AND '31/07/2023' 
    ) AS GIRO_FEV_JUL,
    E.EST_QUAN,
    (VP.TAB_PRC1 * E.EST_QUAN) AS ESTOQUE_VALOR
FROM PRODUTO P 
INNER JOIN ESTOQUE E ON P.PRO_CODI = E.PRO_CODI
INNER JOIN TBVENDAPRO VP ON P.PRO_CODI = VP.PRO_CODI
WHERE P.FOR_CODI = 940
GROUP BY P.PRO_CODI, P.PRO_DESC, E.EST_QUAN, VP.TAB_PRC1
HAVING SUM(VP.TAB_PRC1 * E.EST_QUAN) > 0
ORDER BY P.PRO_DESC;
