SELECT 
    DISTINCT VENDEDOR1.VEN_CODI,
    TBCLIENTE_VENDEDOR1.CLI_CODI AS CLI_CODI,
    VENDEDOR1.VEN_CODI + TBCLIENTE_VENDEDOR1.CLI_CODI AS VEN_CLI,
    CLIENTE1.CLI_NOME AS CLIENTE,
    CLIENTE1.CLI_FANT AS FANTASIA,
    CLIENTE1.CLI_ENDE AS ENDERECO,
    CLIENTE1.CLI_NUME AS NUMERO,
    CLIENTE1.CLI_BAIR AS BAIRRO,
    TBMUNICIPIOS1.MUN_NOME AS CIDADE,
    MAX(CONVERT(CHAR, TBMOVCOMPRA1.MCP_DTEM, 103)) AS DATA
FROM TBCLIENTE_VENDEDOR AS TBCLIENTE_VENDEDOR1
INNER JOIN VENDEDOR AS VENDEDOR1 ON TBCLIENTE_VENDEDOR1.VEN_CODI = VENDEDOR1.VEN_CODI
INNER JOIN CLIENTE AS CLIENTE1 ON TBCLIENTE_VENDEDOR1.CLI_CODI = CLIENTE1.CLI_CODI
INNER JOIN TBMOVCOMPRA AS TBMOVCOMPRA1 ON TBCLIENTE_VENDEDOR1.CLI_CODI = TBMOVCOMPRA1.FOR_CODI
INNER JOIN TBUF AS TBUF1 ON CLIENTE1.UND_CDNAC = TBUF1.UND_CDNAC
INNER JOIN TBMUNICIPIOS AS TBMUNICIPIOS1 ON CLIENTE1.MUN_CODI = TBMUNICIPIOS1.MUN_CODI AND TBMUNICIPIOS1.UND_CDNAC = TBUF1.UND_CDNAC
WHERE  (CLIENTE1.ATI_CODI <> 'AF' AND CLIENTE1.ATI_CODI <> 'VE' AND CLIENTE1.ATI_CODI <> 'FUC')
    AND DATEDIFF(MONTH, TBMOVCOMPRA1.MCP_DTEM, GETDATE()) <= 12
    AND TBMOVCOMPRA1.MCP_TIPOMOV = 'S'
    AND TBMOVCOMPRA1.MCP_DTCAN IS NULL
    AND CLIENTE1.CLI_CODIRESP IS NULL
    AND VENDEDOR1.VEN_CODI = '290'
    AND EXISTS (
        SELECT 1
        FROM TBCLIENTE_VENDEDOR AS TBCLIENTE_VENDEDOR2
        INNER JOIN VENDEDOR AS VENDEDOR2 ON TBCLIENTE_VENDEDOR2.VEN_CODI = VENDEDOR2.VEN_CODI
        WHERE TBCLIENTE_VENDEDOR2.CLI_CODI = TBCLIENTE_VENDEDOR1.CLI_CODI
            AND VENDEDOR2.VEN_CODI = '144'
    )
GROUP BY VENDEDOR1.VEN_CODI, TBCLIENTE_VENDEDOR1.CLI_CODI, CLIENTE1.CLI_NOME, CLIENTE1.CLI_FANT, CLIENTE1.CLI_ENDE, CLIENTE1.CLI_NUME, CLIENTE1.CLI_BAIR, TBMUNICIPIOS1.MUN_NOME
ORDER BY CLIENTE1.CLI_BAIR ASC;
