SELECT 
	MIN(CAST(EXTRACT(YEAR FROM lcc2.DATAEMI_LAN) || '-01-01' AS DATE)) AS DATA ,
	CC.CONTA AS CONTA ,
	cc.DESCRICAO AS descricao ,
	CAST(ROUND(SUM(lcc.VALOR), 2) AS numeric(18, 2)) AS valor , 
	SUBSTRING(CC.CONTA FROM 1 FOR 3) AS ID_NIV1 
FROM LANCAMENTOS_CENTRO_CUSTO lcc 
LEFT JOIN LANCAMENTOS_CONTAS_CORRENTE lcc2 ON lcc.COD_LAN = lcc2.COD_LAN 
LEFT JOIN CENTRO_CUSTO cc ON lcc.COD_CENTRO_CUSTO = cc.CODIGO 
WHERE 1=1
AND SUBSTRING(CC.CONTA FROM 1 FOR 3) IN ('208','213','214','216','221','222')
GROUP BY cc.CONTA , cc.DESCRICAO 
