SELECT 
	s.NOME_SEC AS SECAO , 
	SUM(iv.QUANT) AS QUANTIDADE , 
	ROUND(SUM(iv.QUANT * VALOR), 2) AS TOTAL ,
	SUM(v.TOTAL_VEN) / SUM(SUM(v.TOTAL_VEN)) OVER (PARTITION BY  v.DATA_VEN) AS PERCENTUAL , 
	v.DATA_VEN AS DATA ,
	CASE 	
		WHEN s.NOME_SEC = 'PEIXES' THEN 'PEIXES'
		WHEN s.NOME_SEC = 'EMBUTIDOS E INDUSTRIALIZADOS' THEN 'EMBUTIDOS'
		WHEN s.NOME_SEC = 'BOVINAS' THEN 'BOVINAS'
		WHEN s.NOME_SEC = 'AVES' THEN 'AVES'
		WHEN s.NOME_SEC = 'SUINOS' THEN 'SUINOS' ELSE 'OUTROS'
	END AS SECAO_PART		
FROM ITENS_VENDA iv
LEFT JOIN VENDAS v  ON v.COD_VEN = iv.COD_VEN 
LEFT JOIN PRODUTO p ON iv.COD_PRO = p.COD_PRO 
LEFT JOIN SECAO s ON p.COD_SEC = s.COD_SEC 
GROUP BY 1,5
