SELECT 
	v.DATA_VEN AS DATA_VENDA , 
	v.DATA_VEN AS Ano,
		CASE EXTRACT(MONTH FROM v.DATA_VEN)
			WHEN 1 THEN 'Janeiro'
	        WHEN 2 THEN 'Fevereiro'
	        WHEN 3 THEN 'Março'
	        WHEN 4 THEN 'Abril'
	        WHEN 5 THEN 'Maio'
	        WHEN 6 THEN 'Junho'
	        WHEN 7 THEN 'Julho'
	        WHEN 8 THEN 'Agov.DATA_VENsto'
	        WHEN 9 THEN 'Setembro'
	        WHEN 10 THEN 'Outubro'
	        WHEN 11 THEN 'Novembro'
	        WHEN 12 THEN 'Dezembro'
		END AS Mes ,
	tv.NOME_TPV AS TIPO_VENDA , 
	c.NOME_CLI AS NOME_CLIENTE ,
	v.TOTAL_VEN AS TOTAL_VENDA ,
	ROUND((SUM(iv.QUANT_TROCA * VALOR) - COALESCE(SUM(iv.DESCONTO), 0)), 2) AS VALOR_DEVOLVIDO , 
	ve.NOME_VEND AS VENDEDOR ,
	c.CIDRES_CLI AS CIDADE , 
	pv.COD_PED AS COD_PEDIDO , 
	s.NOME_SUP AS SUPERVISOR
FROM PEDIDO_VENDA pv 
LEFT JOIN VENDAS v ON pv.COD_VEN = v.COD_VEN 
LEFT JOIN VENDEDOR ve ON pv.COD_VEND = ve.COD_VEND 
LEFT JOIN CLIENTE c ON pv.COD_CLI = c.COD_CLI 
LEFT JOIN TIPO_VENDA tv ON PV.COD_TPV = tv.COD_TPV 
LEFT JOIN ITENS_VENDA iv ON pv.COD_VEN = iv.COD_VEN 
LEFT JOIN VENDEDOR_SUPERVISOR vs ON ve.COD_VEND = vs.COD_VEND 
LEFT JOIN SUPERVISOR s ON vs.COD_SUP = s.COD_SUP 
GROUP BY v.DATA_VEN, tv.NOME_TPV, c.NOME_CLI, v.TOTAL_VEN, ve.NOME_VEND, c.CIDRES_CLI, pv.COD_PED, s.NOME_SUP
