SELECT 
	s.NOME_SEC AS SECAO, 
    'CUSTO ' || s.NOME_SEC AS SECAO_CUSTO, 
    SUM(((((IV.QUANT) * IV.VALOR) - coalesce(IV.DESCONTO, 0) + coalesce(IV.ACRESCIMO, 0)) - ((((coalesce(V.DESCONTO_VEN, 0) * 100) / coalesce(((V.TOTAL_VEN + 0.001) + coalesce(V.DESCONTO_VEN, 0)), 1)) * (((IV.QUANT) * IV.VALOR) - coalesce(IV.DESCONTO, 0))) / 100) + ((((coalesce(V.ACRESCIMO_VEN, 0) * 100) / coalesce(((V.TOTAL_VEN + 0.001) - coalesce(V.ACRESCIMO_VEN, 0)), 1)) * (((IV.QUANT) * IV.VALOR) + coalesce(IV.ACRESCIMO, 0))) / 100)))
       AS VALOR_BRUTO ,
    SUM(IV.VALOR_CUSTO * (IV.QUANT - COALESCE(IV.QUANT_TROCA, 0))) AS  VALOR_CUSTO_TOTAL ,
    MIN(CAST(EXTRACT(YEAR FROM V.DATA_VEN) || '-01-01' AS DATE)) AS DATA ,
    --V.DATA_VEN AS DATA , 
	    CASE 	
			WHEN s.NOME_SEC = 'PEIXES' THEN 'PEIXES'
			WHEN s.NOME_SEC = 'EMBUTIDOS E INDUSTRIALIZADOS' THEN 'EMBUTIDOS'
			WHEN s.NOME_SEC = 'BOVINAS' THEN 'BOVINAS'
			WHEN s.NOME_SEC = 'AVES' THEN 'AVES'
			WHEN s.NOME_SEC = 'SUINOS' THEN 'SUINOS' ELSE 'OUTROS'
		END AS SEGMENTACAO
FROM VENDAS v 
INNER JOIN ITENS_VENDA iv ON V.COD_VEN = IV.COD_VEN 
LEFT JOIN PRODUTO p ON P.COD_PRO = IV.COD_PRO 
INNER JOIN SECAO S on P.COD_SEC = S.COD_SEC 
WHERE 1=1
AND IV.CANCELADO = 0 AND IV.VENDA_CANCELADA = 0 
GROUP BY 1,2,6
